#!/bin/bash

alias bashrc='$EDITOR ~/.bashrc'
alias bashaliases='$EDITOR ~/.bash_aliases'
alias cp ='cp -i'
alias mv='mv -i'
alias ip='ifconfig'
alias rm='rm -i'
alias name='uname -a'
alias ll='ls -la'
alias rmd='rm -ri'
alias fin=' grep '
alias psfu='ps -f -u'
alias psk=' ps >> ps.txt ; cat ps.txt | cut -c 1-11 ; rm ps.txt'
alias ps1='echo $PS1'
